### ISSUE TITLE
Switch HTTP testing to use WebMock

### ISSUE THREAD

**Issue by johnbintz** [vinibaggio/outpost#6]
I'm angling to add the ability to set HTTP request headers on Http scouts, and would like to move the HTTP tests to using WebMock to mock requests/responses rather than a stub-thing which is already in there. Testing HTTP should be a lot more fully-featured if this is done. What do you think?

**Comment by vinibaggio** [comment]
I agree! I did my tests this way because it was simple and I didn't have such a need. I will do it as soon as possible.

**Comment by brain-geek** [comment]
Fixed by moving integration tests to fakeweb.
